### ISSUE TITLE
Faster release cycle

### ISSUE THREAD

**Issue by szpak** [4finance/micro-infra-spring#102]
As a user I would like to be able to tests recent changes without waiting too long for a release.

I see two options:
1. Releasing snapshots to bintray.
2. Some kind of Continuous Delivery (automatic new version release by Travis).

In both cases releases shouldn't be done manually.

**Comment by nurkiewicz** [comment]
I believe this issue is basically implemented with #132 and https://github.com/4finance/micro-common-release project. Can we close it or something important is missing?

**Comment by szpak** [comment]
To summarize there is a new project micro-common-release which allows to do automatic releases with `[#DO_RELEASE]` command. Additional issues/enhancements with the mechanism were wrote down in [that project](https://github.com/4finance/micro-common-release/issues).

Documentation is available on the [wiki](https://github.com/4finance/micro-common-release/wiki).
