### ISSUE TITLE
Add automatic retry to fluent RestTemplate calls

### ISSUE THREAD

**Issue by achudzik** [4finance/micro-infra-spring#13]
Hystrix doesn't handle automatic retry by design (see [this tweet](https://twitter.com/HystrixOSS/status/403264396769501185)). Maybe [Spring Retry](http://docs.spring.io/spring-batch/trunk/reference/html/retry.html) can be used instead? All suggestions are welcomed.

**Comment by gotpist1** [comment]
@nurkiewicz Is it possible to use AsyncRetry with Springs AsyncRestTemplate? I messed around abit with it yesterday, but didn't get it to work. Stumbled upon this thread and thought i would ask the expert :)
