### ISSUE TITLE
Versions management in micro-infra-* projects

### ISSUE THREAD

**Issue by szpak** [4finance/micro-infra-spring#132]
Issue to discuss versions management in micro-infra-* projects. Important especially together with automatic releases which should be possible soon (#102).

Two proposed approaches:

1. All the projects have always the same version.
  - Pros:
    - it is always clear which version of dependent projects is used
  - Cons:
    - no way to release only micro-infra-spring
    - all artifacts are released even if there are no changes in the code (though they dependencies were changes, so people using them could see a difference)
   - Bintray could stop liking us one day - after X GB

2. Versions can be different - higher level projects use the latest version released in Bintray (`+` or `latest`)
  - Pros:
    - every project can be released on they own (as an option all upstream projects (but not downstream) can be also automatically released)
  - Cons:
    - harder to get know which subproject version are used

WDYT?
You can edit the issue with your pros/cons (please add your name next to).

**Comment by nurkiewicz** [comment]
This might come in handy when migration is done: https://github.com/IQAndreas/github-issues-import

**Comment by szpak** [comment]
Projects were merged. A method mentioned by @nurkiewicz was used and worked flawlessly.

The only important issue was with duplicated tags - in all projects tags were named `x.y.z` instead of `project-x.y.z`. Because of that tags were manually extracted with a script using [GrGit](https://github.com/ajoberstar/grgit/), renamed and added to the new project with proper prefix.
