### ISSUE TITLE
Support alternative load-balancing options

### ISSUE THREAD

**Issue by nurkiewicz** [4finance/micro-infra-spring#153]
One of our clients needed *sticky* provider strategy instead of default *round-robin* in service provider for exactly one dependency. I think the best way to achieve such option is to add property in `microservice.json`, eg.:

```json
"dependencies": {
        "collerator": {
            "path": "com/ofg/twitter-places-collerator",
            "load-balancer": "sticky"
        }
    }
```

Available options are: *round-robin* (default, allow also *roundrobin* and *round_robin*), *sticky* and *random*, case insensitive. A good place to put load balancing is here: [`ZookeeperServiceResolver`](https://github.com/4finance/micro-deps/blob/3103c21d9f2a678bd70ec915f33523cdce05fd34/src/main/groovy/com/ofg/infrastructure/discovery/ZookeeperServiceResolver.groovy#L59-L60), e.g.:

```groovy
.providerStrategy(new RoundRobinStrategy<Void>())
```

**Comment by mchmielarz** [comment]
Are we going to set a default load balancing strategy in case when configuration provides no such field?

**Comment by nurkiewicz** [comment]
Of course, it must be backward compatible. Default now is AFAIK round-robin (if you don't specify anything).

**Comment by mchmielarz** [comment]
Nevermind, I've just found 'default' word in issue description. ;)
