### ISSUE TITLE
micro-infra-spring 0.7.6 fails with Spring version <4.1

### ISSUE THREAD

**Issue by szpak** [4finance/micro-infra-spring#155]
As it was reported by our users today micro-infra-spring 0.7.6 fails with `NoClassDefFoundError: org.springframework.http.RequestEntity` (class added in Spring 4.1) when used with lower Spring version. Details on HC.

It would be good to investigate if we can simply workaround a problem or we should clearly declare Spring 4.1 as a minimal required Spring version (which if needed looks sensible as there will be [no more updates](https://spring.io/blog/2014/12/30/spring-framework-4-1-4-4-0-9-3-2-13-released) in Spring 4.0.x branch).

**Comment by nurkiewicz** [comment]
Apparently Spring was upgraded deliberately to enable some features around JSON parsing (can't find where exactly). I don't consider this to be a bug.
