### ISSUE TITLE
Swagger not working at all

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/micro-infra-spring#157]
Steps to reproduce:

```
git clone https://github.com/4finance/boot-microservice.git;
cd boot-microservice;
./gradlew bootRun -Dspring.profiles.active=dev
```

go to 

```
/swagger
```

and you get:

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Jan 08 15:41:10 CET 2015
There was an unexpected error (type=Not Found, status=404).
No message available
```

**Comment by nurkiewicz** [comment]
Swagger got broken in https://github.com/4finance/boot-microservice/commit/e1a47d214e3279de253740f8fb3428f8fecc5432. More precisely, Swagger no longer works after upgrading Spring Boot from 1.1.8 to 1.1.9. Investigation is ongoing.

**Comment by nurkiewicz** [comment]
Of course fix will take effect when `boot-microservice` is upgraded to `micro-infra-spring` version 0.8.2+.
