### ISSUE TITLE
Logs from test should not be printed on console

### ISSUE THREAD

**Issue by szpak** [4finance/micro-infra-spring#158]
Only WARN+.

Currently the build of merged `micro-infra-spring` exceeds 10000 lines (with info reporting in Gradle disbled) and is bigger than 4MB (with info reporting in Gradle) which breaks the build.

Related issue is to get tests report (and optionally logs from tests) in case of the failure on Travis. It is suggested to use external data storage (like AWS) to upload important artifacts.

**Update**. In normal mode it look quite ok, but with `--info` stdout output from tests is large. E.g.:
```
./gradlew :micro-deps:micro-deps-spring-config:test --info
```

**Comment by nurkiewicz** [comment]
Duplicate of https://github.com/4finance/micro-infra-spring/issues/129?

**Comment by szpak** [comment]
And that's also issue reported by me :-).
