### ISSUE TITLE
Create acceptance testing via travis

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/micro-infra-spring#160]
In order to be sure that our libraries are not braking the boot-microservice project we could do the following during a Travis build in terms of building micro-infra stack:

  - Build micro-infra-stack
  - Install it locally on travis
  - Clone boot-microservice (it has to have a '+' in terms of micro-infra dependencies)
  - Execute a new task ./gradlew checkHealth that would start boot microservice and run some acceptance tests on it?
  - only if that passes could we start the releasing process

WDYT?

**Comment by szpak** [comment]
Something like that is definitively needed ([#26](https://github.com/4finance/boot-microservice/issues/26) is another example of breaking boot-microservice).

**Comment by szpak** [comment]
I setup acceptance tests on [snap-ci](https://snap-ci.com/4finance/micro-infra-spring/branch/master). boot-microservice is built right after micro-infra-spring.

boot-microservice-gui build is disbled as it is not compatible with micro-infra-spring [0.8.4](https://github.com/4finance/boot-microservice-gui/issues/10) which should be fixed after duplication with boot-microservice is [removed](https://github.com/4finance/boot-microservice-gui/issues/8).

**Comment by szpak** [comment]
Would you like to add anything else to the acceptance build?

**Comment by marcingrzejszczak** [comment]
@thiefik any more ideas other than that?

**Comment by szpak** [comment]
Implemented for boot-microservice with additional [acceptance tests](https://github.com/4finance/boot-microservice/pull/32). Add running also for boot-microservice-gui (when merged).
