### ISSUE TITLE
CorrelationId is not propagated in async context

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/micro-infra-spring#166]
When receviving a request and when passing it to a method that has @Async annotation it we are loosing correlationID info

```
2015-01-13 14:00:58.055+0100 | WARN  |  | SimpleAsyncTaskExecutor-1 | c.o.h.d.n.AbstractNotifier | Exception caught: 
com.ofg.infrastructure.discovery.ServiceUnavailableException: Service with name [com/ofg/reporting/service] is unavailable
	at com.ofg.infrastructure.discovery.ZookeeperServiceResolver.fetchUri(ZookeeperServiceResolver.groovy:73) ~[micro-deps-0.8.2.jar!/:na]
	at com.ofg.infrastructure.web.resttemplate.fluent.ServiceRestClient.forService(ServiceRestClient.groovy:102) ~[micro-infra-spring-base-0.8.2.jar!/:na]
```

**Comment by szpak** [comment]
In which application on hackathon the problem occurred?

**Comment by marcingrzejszczak** [comment]
the one that has `/com/ofg/reporting/service` as a name in its code ;) I have no idea :/

**Comment by nurkiewicz** [comment]
Not true, it's the one that declares dependency on `com/ofg/reporting/service`.

**Comment by marcingrzejszczak** [comment]
Yeah - I forgot that the thrown exception contains resolved path instead of the alias.

**Comment by nurkiewicz** [comment]
Unfortunately during hackathon as much as three services depended on reporting service:

* decisionmaker
* client-service
* loan-application-service

I guess it was in one of them :weary:.

**Comment by szpak** [comment]
The correlationId propagation seems to work correctly. See tests in https://github.com/4finance/boot-microservice/pull/30 and https://github.com/4finance/micro-infra-spring/pull/185.

We suspect that something was misconfigured. Please provide a sample application showing that case.
