### ISSUE TITLE
Automatically expose Hystrix event stream

### ISSUE THREAD

**Issue by nurkiewicz** [4finance/micro-infra-spring#169]
When [micro-infra-hystrix](https://github.com/4finance/micro-infra-spring/tree/master/micro-infra-hystrix) module is on the CLASSPATH, it should automatically expose [Hystrix event stream servlet](https://github.com/Netflix/Hystrix/blob/master/hystrix-contrib/hystrix-metrics-event-stream/README.md). It should be possible to disable it as well and configure context (defaults to `/health/hystrix.stream`?)

**Comment by marcingrzejszczak** [comment]
So @ConditionalOnExpression + a property for the path?
