### ISSUE TITLE
Add option to verify stub invocation with stub-runner

### ISSUE THREAD

**Issue by mariuszs** [4finance/micro-infra-spring#181]
Example:

     wireMock.verifyThat(0, postRequest);

**Comment by nurkiewicz** [comment]
NB: we shouldn't expose WireMock API directly. Instead we should wrap it i.e. to allow using service aliases from `microservice.json` rather than hard-coded network addresses (generated by stub-runner dynamically).

**Comment by nurkiewicz** [comment]
@mariuszs: what do you think about this API: https://github.com/4finance/micro-infra-spring/blob/issues/181/micro-deps/micro-deps-spring-test-config/src/test/groovy/com/ofg/infrastructure/stub/InteractionsSpec.groovy ? It allows verifying internal stubs via WireMock matchers. Will be merged soon.

**Comment by nurkiewicz** [comment]
Apart from comments, LGTM. +1.

**Comment by mariuszs** [comment]
New `Stub` looks great for me. +1

Maybe we can make this api similar to `Mockito.verify(...)`
For ex. `verify(mockedList, never())`, `atLeastOnce())`, `atMost(5)` etc...

**Comment by mchmielarz** [comment]
@mariuszs I'd propose to move the idea of extending the API in Mockito-way to a separate issue if it is not critical.

**Comment by mariuszs** [comment]
+1

**Comment by marcingrzejszczak** [comment]
Looks really cool - will you update the WIKI with some examples? :)

**Comment by mchmielarz** [comment]
@marcingrzejszczak That's the plan. :)
