### ISSUE TITLE
Integrate Hystrix with ServiceRestClient

### ISSUE THREAD

**Issue by nurkiewicz** [4finance/micro-infra-spring#187]
`ServiceRestClient` should have tighter integration with Hystrix, e.g.:

```groovy
.forExternalService()
.retryUsing(...)
.withCircuitBreaker(
    Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey("ExampleGroup"))
                .andCommandKey(HystrixCommandKey.Factory.asKey("HelloWorld"))
.delete()
```

It's important that when retry is configured, every single attempt is wrapped in a separate command, not all retries.

**Comment by marcingrzejszczak** [comment]
So maybe for now remove this GPars usage.

I've added it just for fun ;)

**Comment by szpak** [comment]
@marcingrzejszczak I believe you reply to the wrong issue - did you mean [#30](https://github.com/4finance/boot-microservice/pull/30/files)? Regarding GPars in the end I was able to manage it with a simply [helper method](https://github.com/4finance/boot-microservice/pull/30/files#diff-ee32f18af85e03b70b8facb2c27634a3L12).
