### ISSUE TITLE
Port for Wiremock for external server should not be configurable

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/micro-infra-spring#193]
com.ofg.infrastructure.discovery.web.MockServerConfiguration - the port should be automatically picked instead of being injected

**Comment by nurkiewicz** [comment]
This will also fix #152?

**Comment by szpak** [comment]
Can we close this ticket?

**Comment by marcingrzejszczak** [comment]
I guess so? @nurkiewicz WDYT?
