### ISSUE TITLE
Old jgit version

### ISSUE THREAD

**Issue by szpak** [4finance/micro-infra-spring#210]
Currently `micro-infra-spring-config` uses `org.eclipse.jgit:org.eclipse.jgit:2.3.1.201302201838-r` which is quite old (and also has security issues). Is there a reason to use so old version?

**Comment by nurkiewicz** [comment]
We don't even need this library because we don't interact with git directly in this project. It's possible that it will still work without this library altogether. That being said, it's safe to upgrade.

**Comment by kamilszymanski** [comment]
jgit dependency has been removed
