### ISSUE TITLE
Swagger aceptance tests needed

### ISSUE THREAD

**Issue by szpak** [4finance/micro-infra-spring#211]
Swagger version migration used to generate problems. It is needed to add tests automatically verifying that swagger-ui works properly after upgrade.

It would be probably better to implement them in boot-microservice as we already run it after every commit in micro-infra-spring.

**Comment by thiefik** [comment]
Done,
Added to boot-microservice in:
https://github.com/4finance/boot-microservice/commit/e5c49bf01012b33d84a96ce80d20be676c958e88
