### ISSUE TITLE
Add timeouting startup verifier

### ISSUE THREAD

**Issue by nurkiewicz** [4finance/micro-infra-spring#224]
<a href="https://github.com/marcingrzejszczak"><img src="https://avatars.githubusercontent.com/u/3297437?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marcingrzejszczak](https://github.com/marcingrzejszczak)**
_Tuesday Jul 29, 2014 at 11:25 GMT_
_Originally opened as https://github.com/4finance/micro-deps/issues/3_

----

Upon startup we want to have a possibility to wait for some timeout for a dependency to emerge in zookeeper.

**Comment by marcingrzejszczak** [comment]
Nobody wants to use such a case ;)
