### ISSUE TITLE
Storing properties in ZooKeeper

### ISSUE THREAD

**Issue by nurkiewicz** [4finance/micro-infra-spring#225]
<a href="https://github.com/wybczu"><img src="https://avatars.githubusercontent.com/u/636815?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wybczu](https://github.com/wybczu)**
_Friday Aug 08, 2014 at 13:25 GMT_
_Originally opened as https://github.com/4finance/micro-deps/issues/14_

----

Check posibility of storing properties in ZooKeeper using Archaius lib from netflix:

  https://github.com/Netflix/archaius

Documentation:

  https://github.com/Netflix/archaius/wiki/ZooKeeper-Dynamic-Configuration

We should also keep properties versioned. One posiblity is to create git repo with properties files and microservice, which watch that repo and feed properties to zookeeper.

**Comment by marcingrzejszczak** [comment]
@nurkiewicz @wybczu Can we close this one? We will store properties in Git
