### ISSUE TITLE
Resolve issues with circular dependencies and obligatory microservices

### ISSUE THREAD

**Issue by nurkiewicz** [4finance/micro-infra-spring#226]
<a href="https://github.com/marcingrzejszczak"><img src="https://avatars.githubusercontent.com/u/3297437?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marcingrzejszczak](https://github.com/marcingrzejszczak)**
_Friday Sep 19, 2014 at 07:11 GMT_
_Originally opened as https://github.com/4finance/micro-deps/issues/17_

----

**Comment by marcingrzejszczak** [comment]
All dependencies are not mandatory so the problem is not present.
