### ISSUE TITLE
Add Javadocs

### ISSUE THREAD

**Issue by nurkiewicz** [4finance/micro-infra-spring#227]
<a href="https://github.com/marcingrzejszczak"><img src="https://avatars.githubusercontent.com/u/3297437?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marcingrzejszczak](https://github.com/marcingrzejszczak)**
_Saturday Oct 04, 2014 at 18:31 GMT_
_Originally opened as https://github.com/4finance/stub-runner/issues/11_

----

**Comment by marcingrzejszczak** [comment]
Added Javadocs
