### ISSUE TITLE
Collaborators may go to production with faulty stub definitions

### ISSUE THREAD

**Issue by nurkiewicz** [4finance/micro-infra-spring#229]
<a href="https://github.com/marcingrzejszczak"><img src="https://avatars.githubusercontent.com/u/3297437?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marcingrzejszczak](https://github.com/marcingrzejszczak)**
_Wednesday Dec 17, 2014 at 19:24 GMT_
_Originally opened as https://github.com/4finance/stub-runner/issues/21_

----

Imagine a scenario:

  - I'm a microservice X
  - There's a microservice Y and I'm his collaborator
  - I develop a stub of my microservice (I push it to a repository containing stub definitions)
  - Assuming that we have such a step  I verify whether my stub does exactly what my microservice does
  - I DO NOT pass that verification (my microservice's pipeline gets broken - I won't go to production - which is good)
  - HOWEVER - my collaborator MAY pass the whole pipeline with my broken stubs and go to production

ABSOLUTE MUST:
  - We may only deploy stub definitions of a microservice if they pass the building process (they are structuraly ok and do exactly what a microservice does)

Possible solution:
  - Maybe we should go back to the concept that each microservice publishes two jars - one with fatJar and one with JSON stub definitions
  - Stub-runner would then via microservice.json go to nexus and Grab proper tub definitions (he knows who your collaborator is) 
  - That way it could be easier for us to test if a stub is ok from the microservice's perspective since it's your responsibility as a microservice to deploy your stub - otherwise you won't pass the pipeline

**Comment by nurkiewicz** [comment]
<a href="https://github.com/marcingrzejszczak"><img src="https://avatars.githubusercontent.com/u/3297437?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marcingrzejszczak](https://github.com/marcingrzejszczak)**
_Thursday Dec 18, 2014 at 16:29 GMT_

----

@szimano had an interesting idea:

  - Store in your microservice codebase example of requests
  - Shoot those requests at predefined endpoints
  - Store the response and publish it as a wiremock setup

Potential issue:
  - In this example you send an exact request and get an exact response. What about cases in which you have matchers on the request?

**Comment by nurkiewicz** [comment]
<a href="https://github.com/szimano"><img src="https://avatars.githubusercontent.com/u/289588?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [szimano](https://github.com/szimano)**
_Friday Dec 19, 2014 at 09:13 GMT_

----

when specyfing the stub, we can specify both - the matchers for it, and the exact, example call, which then will be recorded as a response

**Comment by marcingrzejszczak** [comment]
Dealt with http://github.com/Codearte/accurest and the new stub-runner and the proper deployment pipeline
