### ISSUE TITLE
correlationId HTTP header does not fit into convention with "-"

### ISSUE THREAD

**Issue by szpak** [4finance/micro-infra-spring#239]
HTTP headers use "-" to separate words:
```
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: deny
< Content-Security-Policy: default-src 'none'
< Access-Control-Allow-Credentials: true
```
`correlationId` uses camel case. Maybe it would be worth to change it before 1.0.0?

**Comment by nurkiewicz** [comment]
Actually not such a bad idea, **assuming** we remain backward compatible and handle both. We can't afford loosing correlation ID.

**Comment by marcingrzejszczak** [comment]
Will be fixed with Spring Cloud Sleuth integration
