### ISSUE TITLE
Is -Dstubrunner.skip-local-repo=true working?

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/micro-infra-spring#247]
I was executing

```
./gradlew clean buildAll -PdevMode --continue --parallel -Dstubrunner.skip-local-repo=true
```

and the tests failed to pass because of some issues with stubs. When I deleted the proper ~/.groovy/grapes/.... folder then the tests passed. 

We have to check if the switch is actually working.

**Comment by OlgaMaciaszek** [comment]
I had the same problem.

**Comment by mchmielarz** [comment]
It is working. There is an issue with Gradle with copying settings from command line to e.g. test JVM. And this is the reason why it is not working in your cases. Try to add:
```
jvmArgs(project.gradle.startParameter.systemPropertiesArgs.entrySet().collect { "-D${it.key}=${it.value}" })
```
in your build file in test task. Let me know whether it helped.

**Comment by mchmielarz** [comment]
Is the issue solved? If so we could close this ticket.

**Comment by marcingrzejszczak** [comment]
Let's close it for now - I have no reports of it not working. If that will be the case we'll reopen it. WDYT?

**Comment by mchmielarz** [comment]
Agree.
