### ISSUE TITLE
Print out versions of stubs being run

### ISSUE THREAD

**Issue by kamilszymanski** [4finance/micro-infra-spring#248]
at least when using stubs from local repository

**Comment by szpak** [comment]
+1. Related to #240.

Btw, are those stubs versioned? Or we should display commit hash, build date or something else?

**Comment by marcingrzejszczak** [comment]
Timestamp is added to the version

**Comment by marcingrzejszczak** [comment]
In the logs there is info about the downloaded JAR

**Comment by mchmielarz** [comment]
There is version of stubs being used logged but on `DEBUG` level. Should we change it to `INFO`? @kamilszymanski @marcingrzejszczak @szpak

**Comment by szpak** [comment]
+1 for INFO (especially if it would be useful for you)
