### ISSUE TITLE
Shared properties across environments

### ISSUE THREAD

**Issue by dst** [4finance/micro-infra-spring#255]
It would be nice to have common properties for test, stage and prod in one file. Then we will avoid duplication and there will be less problems with maintaining it.

`common` dir next to dev, test or prod can be used for such purpose with lowest priority.

@wybczu , what do you think about it?

**Comment by nurkiewicz** [comment]
+1, we would avoid copying the same properties between environments.

FWIW, it's a matter of adding two extra files here: https://github.com/4finance/micro-infra-spring/blob/e85c4cd870f8c12e58845ca5ee32026d23b544bd/micro-infra-spring-config/src/main/java/com/ofg/infrastructure/property/AppCoordinates.java#L80-L84 (in the beggining).

**Comment by dst** [comment]
It seems that `FileSystemPoller` also needs to be changed.

**Comment by wybczu** [comment]
:+1:

**Comment by marcingrzejszczak** [comment]
Can you also update boot-microservice so that it uses Git based configuration?

**Comment by dst** [comment]
Updating boot-microservice is already reported in an separate issue:
https://github.com/4finance/boot-microservice/issues/21

**Comment by dst** [comment]
Wiki should be edited after merging pull request.

**Comment by dst** [comment]
Wiki updated.
