### ISSUE TITLE
Remove 3rd party SNAPSHOT dependencies (spock)

### ISSUE THREAD

**Issue by tadaskay** [4finance/micro-infra-spring#267]
From my experience, using snapshots of 3rd party libraries in *production* code is an extremely poor decision. Furthermore, it's there only for 8 lines of code in `org.spockframework.runtime.extension.builtin.RestoreSystemPropertiesInterceptor`

Keeping in mind that there is a version conflict between micro-deps and micro-infra-spring on this one (which not all IDEs can resolve), I strongly advise moving to a *release* version of `spock-core` which probably is `0.7-groovy-2.0`

@nurkiewicz @marcingrzejszczak @dainiusvaznys @vadimsjagodins @mvaitkus

**Comment by szpak** [comment]
> From my experience, using snapshots of 3rd party libraries in production code is an extremely poor decision

Make a note that it is only used in test code and micro-infra-spring users do not get SNAPSHOT version into their dependencies. That was a reason to keep spock 0.7-groovy-2.0 in micro-infra-spring-test (which can be a dependency in other systems) which (sometimes) causes mentioned problems with running tests in IDE (Idea does not separate classpath per module :( ).

We moved to to 1.0-SNAPSHOT to be able to use new features (like RestoreSystemPropertiesInterceptor. Spock 0.7 was released over 2 years ago and there is many new featues in master - see among others [here](https://solidsoft.wordpress.com/2014/09/17/whats-new-in-upcoming-spock-1-0-simpler-conditional-test-execution-with-requires-and-ignoreif/) and [here](https://solidsoft.wordpress.com/2014/10/03/whats-new-in-upcoming-spock-1-0-part-2-cleaning-up/)). We later realized that in some cases there are conflicts in Idea.

Nevertheless If the majority agree that using Spock 1.0-SNAPSHOT in test code as something very problematic it should be possible to replace Spock 1.0 dependent code with some other constructions (probably a little bit more verbose or providing more duplication in code).

**Comment by marcingrzejszczak** [comment]
Personally I don't see any problems with keeping that version - quite the contrary I see its benefits (I wouldn't worry about its SNAPSHOT type since it's for test code). @tadaskay you mention about 8 lines of code cause in micro-infra-spring this dependency hasn't been introduced a long time again but quite recently if I'm not mistaken thus people didn't have much time to get acquainted with it.

**Comment by dainiusvaznys** [comment]
So this comes to leading vs. bleeding edge. I think depending on 3rd party
snapshots is a bad idea, even if it is 'for test only' -- I don't see how
that is a valid excuse.
If it is absolutely necessary to use a certain feature set from snapshots
-- create a fork, release under a fixed version and use that while you wait
for the proper version of the original project. Just make sure it fits in
the existing dependency tree.

**Comment by marcingrzejszczak** [comment]
After this PR is merged https://github.com/4finance/micro-infra-spring/pull/303 then this ticket will be obsolete
