### ISSUE TITLE
Fix IP adresses in metric paths

### ISSUE THREAD

**Issue by bogdanaioanei** [4finance/micro-infra-spring#270]
If by any chance the URL intercepted by the MetricsAspect contains an IP address the folder structure in Graphite for example will be misleading. A possible solution is to replace the dots with underscores

**Comment by dst** [comment]
The question is also what to do with port numbers like db:5678 and with domain names like db.4finance.com.

**Comment by wybczu** [comment]
We should replace dots in FQDNs as well, e.g.:

```
'https://foo.f.q.d.n.example.com:5757/api/secure' -> 'foo_f_q_d_n_example_com.5757.api.secure'
```

**Comment by marcingrzejszczak** [comment]
Done in https://github.com/4finance/micro-infra-spring/commit/0987836e96f835186b5ce4890227e684e6602947
