### ISSUE TITLE
Can't reconnect after restarting Graphite

### ISSUE THREAD

**Issue by nurkiewicz** [4finance/micro-infra-spring#277]
When Graphite is restarted, micro-infra-spring can't reconnect to it using standard TCP/IP connector. I guess UDP would solve it, but TCP is still default. You can test it with Docker image containing Graphite:

    docker run --name graphite  -p 8081:80 kamon/grafana_graphite

...and killing it while service runs. Most likely problem lies in CodaHale metrics, so we either fix them or simply advice using UDP (better idea anyway).

**Comment by marcingrzejszczak** [comment]
We could change the default strategy to UDP but that would enforce backwards incompatibility (but only to some extent ;) ). For older versions of micro-infra there was only TCP and the property will be ignored. For the newer versions I also agree that we should go for UDP. WDYT?
