### ISSUE TITLE
Not finding stubs of your collaborators should not result in exceptions

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/micro-infra-spring#292]
It should just mean that your collaborators have not provided any stubs

**Comment by nurkiewicz** [comment]
Exceptions are thrown where? Also is it related to https://github.com/4finance/micro-infra-spring/issues/184 ?

**Comment by marcingrzejszczak** [comment]
No - when Grab is trying to grab the dependency and it can't find any such stub in nexus.

**Comment by cameleeck** [comment]
+1
