### ISSUE TITLE
Disabling git based configuration

### ISSUE THREAD

**Issue by dst** [4finance/micro-infra-spring#324]
We should decide how we want to disable git based configuration if needed.

1. Now: exclude micro-infra-spring-config module (https://github.com/4finance/micro-infra-spring/wiki/Centralized-configuration-management)
2. Use a flag centralized.configuration.enabled or something similar

Any other ideas?

**Comment by dst** [comment]
I vote for 1.

**Comment by kamilszymanski** [comment]
I vote for 2.
Excluding modules means you have to recompile in order to turn it on/off and also forces users that don't want to use git based configuration to remember to exclude the module.

**Comment by szpak** [comment]
There is already a new flag `spring.cloud.bootstrap.enabled` in spring-cloud-config which allows to effectively disable the mechanism. Unfortunately it is defined in [cloud-common](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java) and probably disables all BootstrapConfiguration factories from Spring Cloud.
