### ISSUE TITLE
NoSuchMethodError when upgrading to micro-infra-spring v0.8.13

### ISSUE THREAD

**Issue by mchmielarz** [4finance/micro-infra-spring#334]
When I upgraded to micro-infra-spring 0.8.13 `NoSuchMethodError` exception showed up. It was about missing `javax.servlet.ServletContext.getVirtualServerName()` method which was introduced in `javax.servlet-api:3.1.0` while micro-infra-spring is using `javax.servlet-api:3.0.1` (defined `stub-runner` module).

The problem appeared in runtime and was fixed by adding dependency on `javax.servlet-api:3.1.0` explicitly.

**Comment by szpak** [comment]
Thanks for the report.

`tomcat-embed` provides `servlet-api 3.1.0` inside the JAR. It can conflict with 3.0.1. The problem became visible after `servlet-api 2.5.1` was removed in #321.
