### ISSUE TITLE
Groovy closure as Hystrix fallback

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/micro-infra-spring#338]
When defining circuit breaking with fallback one has to provide that fallback as Groovy closure which makes no sense in the Java world. 

Let's change it to some functional interface.

**Comment by bandrzejczak** [comment]
What should we do with the backwards compatibility? If we change Closure to some functional interface, Groovy code will work, but the Java code below won't:

```java
String result = serviceRestClient.forService("decisionMaker")
                .retryUsing(asyncRetryExecutor.withMaxRetries(5))
                .put()
                .withCircuitBreaker(
                        Setter
                                .withGroupKey(HystrixCommandGroupKey.Factory.asKey("fraudDetection"))
                                .andCommandKey(HystrixCommandKey.Factory.asKey("notifyDecisionMaker"))
                        , new Closure<ResponseEntity>(this) {
                            @Override
                            public String call(Object... args) {
                                logger.info("test close circut");
                                return ResponseEntity.ok().build();
                            }
                        }
                )
                .onUrl("/api/loanApplication_del/"+id)
                .body(fraudVerification)
                .withHeaders()
                    .contentTypeJson()
                .andExecuteFor()
                    .anObject()
                    .ofType(String.class);
```

Should we leave `HttpMethod<U, T> withCircuitBreaker(HystrixCommand.Setter setter, Closure hystrixFallback)` method, but deprecate it, or just change the parameter type?

Another thing is the connection with issue #336. Should the new functional interface for Hystrix fallback  require ResponseEntity as a return type?

**Comment by marcingrzejszczak** [comment]
1) We can't have a closure there - it's not really that easy to define a closure and what we did during a hackathon wasn't really the best practice ;)

IMO we can deprecate the current solution and add a new one with a functional interface. @szpak @nurkiewicz WDYT?

2) #336 - that's totally seperate stuff - I mean why on earth does it work only for `ResponseEntity` ;) We have to first figure it out cause to tell you the truth it should work regardless of the fact whether it's a `ResponseEntity` or not ;)

**Comment by marcingrzejszczak** [comment]
Done here - https://github.com/4finance/micro-infra-spring/pull/344

**Comment by bandrzejczak** [comment]
+1 Great, thanks.
