### ISSUE TITLE
Migrate microservice.json to properties

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/micro-infra-spring#341]
It would be awesome not to have microservice.json at all. Since we have GIT based props - let's keep the microservice descriptor in the yamls.

WDYT?

**Comment by nurkiewicz** [comment]
The location of properties (which files to load) is based on `microservice.json`. So you can't locate `microservice.json` without having it first. Chicken and egg problem.

**Comment by marcingrzejszczak** [comment]
ok so we could have in the application's jar application.yaml with the name of the service and its realm? Would that solve it?

**Comment by nurkiewicz** [comment]
So you would have microservice name/realm in JAR but dependencies in properties repository? I don't see much value in such split.

**Comment by marcingrzejszczak** [comment]
Check out how they do it in Spring Cloud https://spring.io/blog/2015/01/20/microservice-registration-and-discovery-with-spring-cloud-and-netflix-s-eureka - if we did that in a similar way then eventually we could integrate more tightly with Spring Cloud.

**Comment by marcingrzejszczak** [comment]
Done with Spring Cloud Zookeeper https://github.com/4finance/micro-infra-spring/commit/954e9fdf4088fbdb83c4ad14f24190f0876ac502
