### ISSUE TITLE
Change the logging to warn if stubs couldn't have been downloaded

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/micro-infra-spring#342]
Right now it's in error and it's causing some commotion in the logs. Maybe we should donwgrade it to `warn` since it's not an error that stubs haven't been downloaded (maybe the project has just started and the stubs are not there)?

**Comment by mchmielarz** [comment]
For me this we can change it. Since running of the tests is not stopped after such error we could mark log it on warn level. After all there is still full stack trace logged so whole information about the error is preserved.

**Comment by mchmielarz** [comment]
Changed & merged.
