### ISSUE TITLE
Method andExecuteFor() not accessible when used with body() within the ServiceRestClient fluent interface

### ISSUE THREAD

**Issue by MadalinaBidilita** [4finance/micro-infra-spring#402]
After upgrading to version 0.8.18, ServiceRestClient has the following problem when using in a call like:

       ResponseEntity<String> response = serviceRestClient.forExternalService()
                .post()
                .onUrl('/some/url')
                .body(params)
                .andExecuteFor()
                .aResponseEntity()
                .ofType(String)

the method andExecuteFor() is not accessible anymore from body(...)

Another example that might not work:

        String response = serviceRestClient.forService(SERVICE_ALIAS)
                .post()
                .onUrl('/some/url')
                .withoutBody()
                .withHeaders()
                    .contentType(APPLICATION_FORM_URLENCODED)
                .andExecuteFor().anObject().ofType(String.class)

The method anObject() is not accessible from andExecuteFor()

Cause: ResponseReceiving interface does not extend anymore Executable<T>.

**Comment by kamilszymanski** [comment]
fixed by #408
