### ISSUE TITLE
Possibility to communicate with microservices from a different realm

### ISSUE THREAD

**Issue by bogdanaioanei** [4finance/micro-infra-spring#423]
Hello,

I'm sure this was taken into consideration and talked about in the past but some people are still wondering why is there a restriction for allowing microservices to communicate only within a certain realm. Let's have a discussion and elucidate the reasons for this :)

Why wouldn't two sets of microservices that are in different realms (A and B for example) be able to communicate via REST with a microservice in another realm (C for example)?

With the current state of micro-infra-spring the only workaround would be, as discussed with @marcingrzejszczak, to integrate the microservices from different realms via JMS. That would work but we would lose some advantages we have right now thanks to Zookeeper.

So what do you think? Please share your thoughts and opinions :)

Thanks!

**Comment by me3x** [comment]
Let's use country specific realm even for core services or stop using realms at all. Microservice.json could be parametrized and filled during build with gradle.

**Comment by dstepanov** [comment]
+1 I don't like restrictions ;)

**Comment by marcingrzejszczak** [comment]
With spring-cloud-zookeeper there will be ways to do that. For now it's impossible and we are deliberate on that.
