### ISSUE TITLE
Command line properties should have precedence over git properties

### ISSUE THREAD

**Issue by szimano** [4finance/micro-infra-spring#457]
now they don't

**Comment by szpak** [comment]
It seems to be a feature in [spring-cloud-config](https://github.com/spring-cloud/spring-cloud-config/issues/167), but I agree it is not intuitive.. I haven't tested it personally, but @cameleeck reported that `spring.cloud.config.overrideSystemProperties=false` helps. It is put into global.yaml, but maybe we would like to make it default for micrfo-infra-spring-config.

**Comment by cameleeck** [comment]
As said @szpak you need to pass this flag to your configuration. Mechanisms under the spring-cloud-config do not matched overriding way written down in spring-boot [documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html)

**Comment by marcingrzejszczak** [comment]
@szpak - any idea how to do it properly other than sth like this (this is pseudocode):

```groovy
@Confguration
class SomeConfig {

@PostConstruct //or @Autowired
void settingUpSystemPropertyViaSomeMethod() {
System.setProperty('spring.cloud.config.overrideSystemProperties', System.getProperty('spring.cloud.config.overrideSystemProperties', 'true'))
}

}
```

**Comment by spencergibb** [comment]
couldn't you just create a `PropertySource` with that value?  Like [this](https://github.com/spring-projects/spring-boot/blob/e3b59774c8444346c456d800a5fbb70b2f5735ae/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/EndpointWebMvcAutoConfiguration.java#L175)

**Comment by marcingrzejszczak** [comment]
@spencergibb - indeed sounds like a far better idea :)

**Comment by marcingrzejszczak** [comment]
BTW @spencergibb - any ideas when will release a milestone version of sleuth and zookeeper?

**Comment by spencergibb** [comment]
when I have time :-)  I was off for a week (moved back home) and am prepping for OSCON next week.

**Comment by marcingrzejszczak** [comment]
ok :) Just ping us however, wherever once you do it :P For sure I've forgotten to move some stuff so most likely you'll get a few PRs from our side to Zookeeper to ensure that everything is working as it should :)

**Comment by marcingrzejszczak** [comment]
@spencergibb 

having such a piece of code:

```
@Override
    public void afterSingletonsInstantiated() {
        addLocalManagementPortPropertyAlias((ConfigurableEnvironment) applicationContext.getEnvironment());
    }

    /**
     * Turn on by default of overriding system properties
     * @param environment the environment
     */
    private void addLocalManagementPortPropertyAlias(
            final ConfigurableEnvironment environment) {
        environment.getPropertySources().addFirst(
                new PropertySource<Object>("Spring Cloud customization") {
                    @Override
                    public Object getProperty(String name) {
                        if ("spring.cloud.config.overrideSystemProperties".equals(name)) {
                        return environment.getProperty("spring.cloud.config.overrideSystemProperties", "false");
                    }

                    return null;
                    }
                });
    }
```

doesn't really work. This property is completely ignored. I tried to create a custom bean that would override the prop:

```
@Bean
    @Primary
    PropertySourceBootstrapProperties propertySourceBootstrapProperties() {
        PropertySourceBootstrapProperties propertySourceBootstrapProperties = new PropertySourceBootstrapProperties();
        propertySourceBootstrapProperties.setOverrideSystemProperties(false);
        return propertySourceBootstrapProperties;
    }
```
And the problem is that here: https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java#L138 a prop is not taken from https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java#L67 (in fact this field is unsed) but it's generated via `new` so my version gets ignored.

For sure I screwed sth and that's why it's not working but maybe you have an idea what's going on? :P

**Comment by modestukasai** [comment]
Hi, 
according to documentation from [spring cloud (Customizing the Bootstrap Property Sources)](http://projects.spring.io/spring-cloud/spring-cloud.html#customizing-bootstrap-property-sources) this property override can be done by adding config to `micro-infra-spring-config`:
```java
@Configuration
public class SpringCloudAdditionalPropertySourceLocator implements PropertySourceLocator {
    @Override
    public PropertySource<?> locate(Environment environment) {
        return new MapPropertySource("microInfraSpringCloudConfigSource",
                Collections.<String, Object>singletonMap("spring.cloud.config.overrideSystemProperties", "false"));
    }
}
```
And add below property to `META-INF/spring.factories`
```
org.springframework.cloud.bootstrap.BootstrapConfiguration=com.ofg.infrastructure.property.SpringCloudAdditionalPropertySourceLocator 
```

After these changes [PropertySourceBootstrapConfiguration](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java#L138) recognizes command line properties.

Can I proceed with this change/addition in `micro-infra-spring-config`?

**Comment by marcingrzejszczak** [comment]
Looks great! Please proceed :) I would rename the class to sth like `SystemPropertiesOverridingPropertySourceLocator`. WDYT?

**Comment by marcingrzejszczak** [comment]
Ah and remember that if you want this feature to be applicable for applications that don't have Spring Boot you have to update the `legacy` branch

**Comment by modestukasai** [comment]
Thank you for naming :) It looks better than mine :)

I can merge changes to legacy branch also.
