### ISSUE TITLE
License file doesn't contain the owner name

### ISSUE THREAD

**Issue by tadaskay** [4finance/micro-infra-spring#464]
Instead there's: `Copyright {yyyy} {name of copyright owner}`

**Comment by szpak** [comment]
Are you about the LICENSE file?
https://github.com/4finance/micro-infra-spring/blob/master/LICENSE#L189

**Comment by tadaskay** [comment]
Indeed

**Comment by szpak** [comment]
It is in a section `APPENDIX: How to apply the Apache License to your work.`. I'm not a layer, but as I understand the text above:
```
      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "{}"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.
```
the information that a project is licensed under the terms on the Apache License (with filled the copyright owner name) should be placed in README and/or other important files (like production code).

**Comment by tadaskay** [comment]
You're right. I missed that this is 'HOW TO' embedded in a license file itself :)
