### ISSUE TITLE
microservice.config.file is not working when provided from properties - even though the property is resolved before is used microservice.config.file

### ISSUE THREAD

**Issue by S2lomon** [4finance/micro-infra-spring#474]
We are adding properties file to be taken under consideration with microservice.config.file property pointing at custom microservice.json, that resides under same path. 

Unfortunately, during execution such exception is thrown: java.io.FileNotFoundException: class path resource ['classpath:taken-from-property-microservice.json']. What's even more disturbing, when we're providing same property via System.setProperty, all is working just fine.

[branch](https://github.com/4finance/micro-infra-spring/tree/issues/474-adding-tests-documenting-this-issue) with tests documenting this behavior

**Comment by marcingrzejszczak** [comment]
You've made a mistake in the YAML file

instead of:

```yaml
microservice.config.file: 'classpath:service-configuration-resolver-microservice.json'
```

you should have written:

```yaml
microservice.config.file: classpath:service-configuration-resolver-microservice.json
```

http://stackoverflow.com/questions/19109912/do-i-need-quotes-for-strings-in-yaml

PS.
I hate YAML

**Comment by S2lomon** [comment]
You're right. It's an issue with the interpretation of properties in Spring. Now at least it makes sense.
