### ISSUE TITLE
In non-production environment start Zookeeper only after ServiceResolver has been accessed

### ISSUE THREAD

**Issue by dstepanov** [4finance/micro-infra-spring#479]
```groovy
@ContextConfiguration(classes = [com.ofg.infrastructure.base.BaseConfiguration, ServiceDiscoveryConfiguration])
class LazySpec extends Specification {

    def "simple test"() {
        given:
            def a = 1;
        expect:
            a == 1
    }

}
```
This code should't start Zookeeper instance or use Curator etc.

Laziness should be introduced in Spring Beans configurations: to make a bean lazy the bean factory method should be annotated with ```@Lazy``` and all occurrences too, then Spring will create a proxy and initialize it on the first access.

**Comment by marcingrzejszczak** [comment]
Actually I disagree.

Since you've added a configuration with ServiceDiscovery I assume that you
know what you're doing. You want to register your app upon application
startup.

If you don't want this to happen for tests pick those spring configs that
you need and that's it.

**Comment by dstepanov** [comment]
In this case, yes, but in most cases you have only one base class that's includes all your configuration and then you end up with slower start of your tests... 

Maybe it doesn't really matter, but I would prefer application that starts fast and doesn't load stuff that isn't going to use.

**Comment by marcingrzejszczak** [comment]
So change the tests then... :)

When you need to register in Zookeeper load up the config. If no then don't
do it. It's that simple ;)
