### ISSUE TITLE
Missing source (link) for micro-infra-hystrix

### ISSUE THREAD

**Issue by cforce** [4finance/micro-infra-spring#480]
I can't find the source for the correlationId support for hystrix. Please update your doc.

**Comment by marcingrzejszczak** [comment]
It was there all the time: https://github.com/4finance/micro-infra-spring/wiki/CorrelationId-setting#hystrix 

Is it what you were looking for?

**Comment by cforce** [comment]
Almost. I was looking for the source code link in the first section of your link "Additionally we support Hystrix. micro-infra-hystrix co"
https://github.com/4finance/micro-infra-spring/tree/master/micro-infra-hystrix -> 404

**Comment by nurkiewicz** [comment]
In the past we had separate component or Hystrix but in the meantime it was merged into other modules. The link was dead and I simply removed it. There is no extra documentation, thanks for reportin.

**Comment by cforce** [comment]
Can you point me to the source (files) where this implementation lives. Tx.

**Comment by nurkiewicz** [comment]
Sure:

https://github.com/4finance/micro-infra-spring/blob/master/micro-infra-spring-base/src/main/java/com/ofg/infrastructure/hystrix/CorrelatedCommand.java

https://github.com/4finance/micro-infra-spring/blob/master/micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/hystrix/CorrelatedCommandSpec.groovy

**Comment by cforce** [comment]
tx
