### ISSUE TITLE
It's not possible to use application offline with micro-infra

### ISSUE THREAD

**Issue by tadaskay** [4finance/micro-infra-spring#482]
`Resolving dependency [group:com.ofg, module:stub-definitions, version:*, transitive:false] location in remote repository...`

Obviously there should be some fallback and not fail everything just because the stubs aren't available or <insert any other reason here>.

**Comment by marcingrzejszczak** [comment]
What flags did you pass?

**Comment by marcingrzejszczak** [comment]
In version 0.9.2 (I'm about to release it) it will be available that local repo never reaches remote repo. Nobody has released micro-infra since my change.

**Comment by tadaskay** [comment]
No flags
