### ISSUE TITLE
Health check on application created with micro-infra-spring returns system down

### ISSUE THREAD

**Issue by karolkalinski** [4finance/micro-infra-spring#485]
How to reproduce bug:
1. Run boot-microservice application (`gradlew run` or from IDE)
2. Enter endpoint `/health`, e.g. `http://localhost:8080/health`
3. Check the result, in log you can see
````
2015-08-11 14:58:13.982+0200 | ERROR |  | main | o.s.c.c.c.ConfigServicePropertySourceLocator | Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/bootstrap/dev/master":Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
````

The issue is caused by presence of bean `org.springframework.cloud.config.client.ConfigServerHealthIndicator` in the context. It calls `org.springframework.cloud.config.client.ConfigServicePropertySourceLocator` and checks if property value can be found, but it fails.
Both mentioned beans are conditional on value *spring.cloud.config.enabled*.

**Comment by modestukasai** [comment]
Hi,
I'm not able to reproduce this issue and I'm not able to contact karol kalinski.
Please contact me if possible.
Thanks!

**Comment by nurkiewicz** [comment]
CC @karolkalinski - up.

**Comment by modestukasai** [comment]
I have tried to contact him via skype and now via email and hipchat. 
Thanks!

**Comment by karolkalinski** [comment]
Confirmed. The problem does not exist anymore.
