### ISSUE TITLE
Stubs and microservice name for different products 

### ISSUE THREAD

**Issue by cameleeck** [4finance/micro-infra-spring#502]
As a developer i want to have different product names for same microservice.
Currently we looking stubs under collaborator path + -stubs suffix. Due this limitation we need to publish same stubs under different artifactId. 
e.g 
***microservice.json:***
```
this: 'a/b/c/microservice-product'
```
***downloaded stubs:***
```
a.b.c.microservice-product-stubs
```
but inside repository we have only 
```
a.b.c.microservce-stubs
```

**Comment by marcingrzejszczak** [comment]
After discussions we should do the same thing as I proposed to do when our stuff gets migrated to Spring Cloud Commons. 
We can in microservice.json provide the "artifactId" and "groupId" fields.

```json
"pl" {
"this": "/a/b/c/foo-service",
"dependencies": {
"alias" : {
"groupid": "a.b.c",
"artifactId": "another-service"
}
}
}
```

Kudos to @S2lomon for the hint :)

**Comment by cameleeck** [comment]
Maybe use convention gathered from gradle dependency ? So we will have single line param e.g: 
```
"pl" {
    "this": "/a/b/c/foo-service",
    "dependencies": {
        "alias" : {
            "path" : "/a/b/c/another-service-productX",
            "stubs" : "a.b.c:another-service-stub:classifer"
        }
    }
}
```
It will be more configurable and everyone can have different way of naming stubs. Code won't be more complicated that introduced in pull request.

**Comment by marcingrzejszczak** [comment]
That was one of the ideas to use Gradle convention. On the other hand I have everything already parsed and don't have to think about parsing via `:`

In your case it would be:

```json
"pl" {
    "this": "/a/b/c/foo-service",
    "dependencies": {
        "alias" : {
            "path" : "/a/b/c/another-service-productX",
            "stubs" : "a.b.c:another-service:stub"
        }
    }
}
```

**Comment by marcingrzejszczak** [comment]
I've checked stub-runner manually using the following command on boot-microservice:

`./gradlew :stub-runner:stub-runner:run -Pargs='-c pl -minp 10000 -maxp 10005 -n com/ofg/twitter-places-analyzer -md -zl localhost:2181 -s -sr http://dl.bintray.com/4finance/micro'`

Much to my surprise it did work ;)

The `/microserviceDescriptor` and `/microservice.json` have the following structure (for boot-microservice):

```
{
  "pl": {
    "dependencies": {
      "collerator": {
        "path": "com/ofg/twitter-places-collerator",
        "stubs": "com.ofg:twitter-places-collerator:stubs"
      }
    },
    "this": "com/ofg/twitter-places-analyzer"
  }
}
```

**Comment by S2lomon** [comment]
All in all, looks great :) (especially after using the "colon separated" dependency convention ;))

**Comment by marcingrzejszczak** [comment]
I think that was your suggestion to use that in the first place. Kudos :)

I thought that it will take more effort to rewrite it like that.

I forgot to update the docs - I'll try to do it tomorrow.

**Comment by S2lomon** [comment]
Yep. that's why I like it so much - good job ;)

**Comment by marcingrzejszczak** [comment]
Done in https://github.com/4finance/micro-infra-spring/commit/fd76ff56552991197654b7cfc56569adc7cd79ed
