### ISSUE TITLE
Metrics flooding  - improper usage of rest client in time of  URL construction

### ISSUE THREAD

**Issue by maciekpe** [4finance/micro-infra-spring#514]
Improper usage of rest client fluent API in time of URL construction leads to generate redundant metric's keys.

**Comment by maciekpe** [comment]
Proposed solution is to switch off sending keys with name "*RestOperation*" by default.

**Comment by maciekpe** [comment]
Current workaround : network level filters for UDP communication

**Comment by nurkiewicz** [comment]
+1. The problem is with requests like:

    onUrl('http://some.address.com/api/whatever/123')

where `123` is a dynamic parameter. For every unique ID we create new metric. Instead URL with template should be used, but not many users know about it, so it's better to disable this feature by default.

**Comment by maciekpe** [comment]
Thanks to hint from Tomek:

https://github.com/4finance/micro-infra-spring/blob/master/micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/ServiceRestClientConfigurationSupport.groovy#L132 

it seems to be easy change
 
'${rest.client.metrics.enabled:false}

**Comment by maciekpe** [comment]
Fixed in https://github.com/4finance/micro-infra-spring/tree/issue/539-permature_end_of_file_obfus

**Comment by maciekpe** [comment]
Fixed in legacy & master

**Comment by maciekpe** [comment]
Fixed in legacy & master
