### ISSUE TITLE
Create migration guide to version 2.0

### ISSUE THREAD

**Issue by kamilszymanski** [4finance/micro-infra-spring#518]

**Comment by marcingrzejszczak** [comment]
There's no migration guide/ The version is backwards compatible.

**Comment by marcingrzejszczak** [comment]
Any possible issues are described here: https://github.com/4finance/micro-infra-spring#troubleshooting-spring-cloud-integration

**Comment by kamilszymanski** [comment]
Backwards compatible - WOW, great job! :+1: 

But still a small note on backwards compatibility would be nice

**Comment by marcingrzejszczak** [comment]
Added info to the readme: https://github.com/4finance/micro-infra-spring/blob/master/README.md#version-greater-than-200
