### ISSUE TITLE
Hardcoded env in FileSystemLocator

### ISSUE THREAD

**Issue by marekpribyl** [4finance/micro-infra-spring#553]
There is a hardcoded **env** param which prevents loading properties for environments other than **prod**:

`
final org.springframework.cloud.config.environment.Environment loadedEnvs =
                springEnv.findOne(appCoordinates.getPath(), "prod", null);
`

Should be:

`
final org.springframework.cloud.config.environment.Environment loadedEnvs =
                springEnv.findOne(appCoordinates.getPath(), appCoordinates.getEnvironment(), null);
`

**Comment by szpak** [comment]
Good catch. For the report.
