### ISSUE TITLE
StubRunnerConfiguration throws MicroserviceConfigurationNotPresentException if no dependencies

### ISSUE THREAD

**Issue by ptrts** [4finance/micro-infra-spring#563]
StubRunnerConfiguration throws MicroserviceConfigurationNotPresentException if there are no dependencies in bootstrap.yml

**Comment by cameleeck** [comment]
@ptrts Can you provide a use-case for this issue or explain more clearly your issue ?

**Comment by ptrts** [comment]
Sure.
1. Create a microservice project without dependencies on other microservices in it's bootstrap.yml
2. Try to run it with no "prod" Spring profile active
3. On the startup you'll get MicroserviceConfigurationNotPresentException thrown

**Comment by me3x** [comment]
https://github.com/spring-cloud/spring-cloud-zookeeper/issues/74

**Comment by cameleeck** [comment]
As we talked with @me3x for achieve that you need to pass this property: spring.cloud.dependency.enabled: true It was repaired in latest micro-infra-spring release.
